version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real-estate
    command: [ 'postgres', '-c', 'wal_level=logical' ]
    healthcheck:
      test: [ 'CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      api-processing:
    volumes:
      - postgress-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 8082
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      api-processing:


  processing:
    build:
      context: ./api
    image: processing:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: default
      # Add other env vars as needed
    networks:
      api-processing:

  int-test:
    build:
      context: ./int-test
    image: int-test:latest
    depends_on:
      - processing
    environment: {}
    # Uncomment to run interactively
    # stdin_open: true
    # tty: true
    networks:
      api-processing:

networks:
  api-processing:
    name: api-processing
    driver: bridge

volumes:
  pgadmin-data:
  postgress-data:
  minio-data:
